#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "To uninstall ThirdEyeSearch, this script must be ran as the root user."
    exit 1
fi

rm -rf /usr/local/ThirdEyeSearch
rm -rf /etc/ThirdEyeSearch/

rm  /usr/bin/thirdeyesearch